image: node:lts-alpine

# Cache modules in between jobs: https://docs.gitlab.com/ee/ci/caching/#caching-nodejs-dependencies
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

before_script:
  # - npm install hexo-cli -g
  - npm ci --cache .npm --prefer-offline

test:
  script:
    - npm run build
  except:
    - main

pages:
  script:
    - npm run build
    # Compress assets
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\|svg\|xml\)$' -exec gzip -f -k {} \;
  artifacts:
    paths:
      - public
  only:
    - main
