name: Test
env:
  NODE_ENV: production

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Build website
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Restore last modified time
      run: "git ls-files -z | while read -d '' path; do touch -d \"$(git log -1 --format=\"@%ct\" \"$path\")\" \"$path\"; done"
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Cache Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Build website
      run: npm ci && npm run build
